### ISSUE TITLE
Question: best practice for external services like audio and video services ?

### ISSUE THREAD

**Issue by mohammadne** [Flutterando/Clean-Dart#12]
Hi.

thanks to your nice repo, 
in my usecase, I have to implement an ```AudioService```, the way I have implement it is:
1- define an interface in domain
2- implement it in infra
3- use it as a dependency to a cubit into my presentation layer and then, in my view, I used the cubit only.

the questions are:
1- as you said,  we have ```External``` layer and I think my implementation is wrong and I think that I have to put the implementation in  ```External``` layer rather than ```infra```.

2- it would be awesome if you clarify that when do we should use ```External``` layer ?

3- what are the Drivers ?

Thanks.

**Comment by Bwolfs2** [comment]
In this approach we  have 2 mutable layer Presenter/View and External, cuz in the Presenter u can use today Bloc, and tomorrow u want to change to Mobx or just SetState and the rest of code will be unchanged and all will keep working. When u thinking on the External is the same way, u can work today with ur own Api and tomorrow change to Firebase or Hasura and u will just create another Extenal Layer (and change the injection) and 'vouala' all will keep working =)
So thinking in this approach Domain and Infra need to be minimal package dependencies (if u use just Dart will be better, but we use Dartz to facilitate somethings)

**Comment by mohammadne** [comment]
thanks for clarification about ```presenter``` and ```External```, so I should definitely put my service implementations inside of ```External```, 

but [in the picture](https://github.com/Flutterando/Clean-Dart/blob/master/imgs/img1.png) as it says, we have to implement services inside of ```infra``` layer, 
in my case I am using [just_audio](https://pub.dev/packages/just_audio) with [audio_service](https://pub.dev/packages/audio_service), and I defined a service interface for it inside domain and implement it inside of ```infra```, it would be awesome if you clarify what interfaces and ... we have to use inside ```infra``` and ```External``` for ```audio_service``` (and in general it could be any service).

because as I explain my approach above, the ```infra``` layer **can not be minimal package dependent**.

Thanks ;-D

**Comment by Bwolfs2** [comment]
I guess the best way is put the Implementation of this services like AudioService, but what name we can use... hmmm... i believe is what we are calling Driver... I guess Drivers was to Local things like Audio, Camera, wifi... But the name... i u have any sugestion i want to hear... In my [sample ](https://github.com/Bwolfs2/task_clean_app) i use DAO to name database access (i'm forced for the package Floor).

But names is just names, OK? u can call whatever name u think is better, u just need be in mind the separation Presenter(mutable),Domain and Infra(Imutable), External(Mutable), External in my mind is not a good name cuz looks like just External Access(like APIs) but this is just External the Business rule

**Comment by Bwolfs2** [comment]
the Infra Layer is just a Bridge between Domain/UseCases and Datasources/External.... I don`t like the name Infra too :C But make sense to someone, and we adopt it :)

To be honest when i'm start to use CleanDart my External was called Infra

**Comment by Bwolfs2** [comment]
I see in some cases people using 3 layers: Presenter(Muttable),Domain(Imuttable), Infra(Muttable) and the implementation will be all in Infra. If u are using just 1 project the project with External looks like a Over Engineering but when u work with separated projects 1 for Presenter 1 for Domain+Infra and 1 for External its make more sense

**Comment by mohammadne** [comment]
thanks @Bwolfs2

> I see in some cases people using 3 layers: Presenter(Muttable),Domain(Imuttable), Infra(Muttable) and the implementation will be all in Infra. If u are using just 1 project the project with External looks like a Over Engineering but when u work with separated projects 1 for Presenter 1 for Domain+Infra and 1 for External its make more sense

my case is the first one, so I will go ahead with that ;)

**Comment by Bwolfs2** [comment]
Nice =)

But always make sure that the business rule, validations etc ... stay in the domain, because if you ever need to change your Datasource / Repositories because you will switch from Api to firebase (or firebase to an Api) you will avoid losing any validation or business rule .. And it will happen if you do not leave the rule in the Domain layer =D
