### ISSUE TITLE
Question: best practice for defining environments ?

### ISSUE THREAD

**Issue by mohammadne** [Flutterando/Clean-Dart#13]
Hi.

what I will do in my apps is to defining an ```ENV``` interface and some implementations for that by specifying the flavor via ```Injectable``` package.

as I can see in examples, there are some ```.env``` files, it is the first time that I have seen these files, 

can I ask that which one do you prefer to use ? 

Thanks

**Comment by Bwolfs2** [comment]
@rodrigorahman u can answer this

**Comment by Ascenio** [comment]
There may be more, but generally I think about two good practices:

1. If you want to set **variables** based on staging, or development or release, just use `--dart-define`. You can read more about it [here](https://itnext.io/flutter-1-17-no-more-flavors-no-more-ios-schemas-command-argument-that-solves-everything-8b145ed4285d).

2. If you want to execute different **code**, say configuring _InMemory_ repositories for debug and _Remote_ repositories with [get_it](https://pub.dev/packages/get_it), you can define a _main_ for each one of them. 
```bash
$ flutter run -t lib/development.dart
$ flutter run -t lib/staging.dart
$ flutter run -t lib/release.dart
```

**Comment by tauamendonca** [comment]
Closed as Asceno gave an answer and there was no follow up for a while.
